services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    Lukasbableck\ContaoTitleDescriptionBundle\:
        resource: ../src
    Lukasbableck\ContaoTitleDescriptionBundle\EventListener\:
        resource: ../src/EventListener
        public: true